version: 2.1
orbs:
  node: circleci/node@4.1.0
  docker: circleci/docker@1.1.3  # Add the Docker orb
  eslint: arrai/eslint@2.0.0

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install

  test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run test

  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

  deploy:
    executor: docker/default  # Use Docker executor for deployment
    steps:
      - checkout
      # Add your Docker build and push steps here

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - test
      - deploy:
          requires:
            - lint
